In [1]:
import numpy as np

1. ndim will tell you the number of axes (dimensions) of an array.

2. size will tell you the total number of elements of the array, which is the product of the elements of the array’s shape.

3. shape will display a tuple of integers that indicate the number of elements in each dimension of the array. 

In [2]:
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)
print("Ndim:",arr1.ndim)
print("Size",arr1.size)
print("Shape",arr1.shape)

[10 20 30 40 50]
Ndim: 1
Size 5
Shape (5,)


In [3]:
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)
print("Ndim:",arr1.ndim)
print("Size",arr1.size)
print("Shape",arr1.shape)

[[1 2 3]
 [4 5 6]]
Ndim: 2
Size 6
Shape (2, 3)


In [4]:
arr1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1)
print("Ndim:",arr1.ndim)
print("Size",arr1.size)
print("Shape",arr1.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]
Ndim: 3
Size 18
Shape (3, 2, 3)


In [5]:
# To access an array element
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1[1])

20


In [6]:
# To access an array element
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1[1,0])

4


In [7]:
# To access an array element
arr1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1[0,0,0])

1


In [8]:
# To access an array element
arr1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1[-1,-1,-1])

26


In [9]:
# To access an array element
arr1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1[-1,-1])

[24 25 26]


In [10]:
# To access an array element
arr1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1[0,0])

[1 2 3]


In [11]:
# To access an array element
arr1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1[0])

[[1 2 3]
 [4 5 6]]


In [12]:
# To access an array element
arr1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1[1])
print()
print(arr1[1,0])
print()
print(arr1[1,0,1])

[[11 12 13]
 [14 15 16]]

[11 12 13]

12


In [13]:
# To access an array element
arr1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1[1,-1])

[14 15 16]


## Slicing

In [14]:
arr1 = np.arange(10)
print(arr1)
print()
print(arr1[0:4])
print(arr1[5:-1])

[0 1 2 3 4 5 6 7 8 9]

[0 1 2 3]
[5 6 7 8]


In [15]:
arr1 = np.arange(10)
print(arr1)
print()
print(arr1[-1:])
print(arr1[4:])

[0 1 2 3 4 5 6 7 8 9]

[9]
[4 5 6 7 8 9]


In [16]:
arr1 = np.linspace(10, 100, 10)
print(arr1)
print()
print(arr1[arr1<50])
print(arr1[arr1>50])
print(arr1[arr1==50])
print(arr1[arr1!=50])

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]

[10. 20. 30. 40.]
[ 60.  70.  80.  90. 100.]
[50.]
[ 10.  20.  30.  40.  60.  70.  80.  90. 100.]


In [17]:
arr1 = np.linspace(10, 100, 10)
print(arr1)
print()
index = (arr1 >50)
print(index)
print(arr1[index])
print()
index = (arr1 < 50)
print(index)
print(arr1[index])
print()
index = (arr1 == 50)
print(index)
print(arr1[index])

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]

[False False False False False  True  True  True  True  True]
[ 60.  70.  80.  90. 100.]

[ True  True  True  True False False False False False False]
[10. 20. 30. 40.]

[False False False False  True False False False False False]
[50.]


In [18]:
arr1 = np.arange(0, 100, 5)
print(arr1)
print()
print(arr1[arr1==(30+50)])
print()
print(arr1[arr1%15==0])
print()
print(arr1[arr1%15!=0])

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

[80]

[ 0 15 30 45 60 75 90]

[ 5 10 20 25 35 40 50 55 65 70 80 85 95]


In [19]:
arr1 = np.arange(0, 100, 5)
print(arr1)
print()
print(arr1[arr1%15==0])
print()
print(arr1[(arr1%15==0) & (arr1>50)])

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

[ 0 15 30 45 60 75 90]

[60 75 90]


In [20]:
arr1 = np.arange(0, 100, 5)
print(arr1)
print()
print(arr1[arr1%15==0])
print()
print(arr1[arr1>80])
print()
print(arr1[(arr1%15==0) | (arr1>80)])

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

[ 0 15 30 45 60 75 90]

[85 90 95]

[ 0 15 30 45 60 75 85 90 95]


## Some basic methods to create array in numpy are
1. np.array()
2. np.ones()
3. np.zeros()
4. np.empty()
5. np.linspace()
5. np.arange()

In [21]:
# Create an array using np.array
arr1 = np.array([2,3,4], dtype=np.int16)
arr2 = np.array([10, 11, 12], dtype=np.float32)
arr3 = np.array(9)
print(arr1, arr2, arr3)

# Check a variable an instance of an array
print(isinstance(arr3, np.ndarray))

[2 3 4] [10. 11. 12.] 9
True


In [22]:
# Create an array of ones using np.ones() method

arr1 = np.ones(4)
print(arr1, arr1.dtype)

arr2 = np.ones(4, dtype=np.int16)
print(arr2, arr2.dtype)

arr3 = np.ones((3,3), dtype=np.int16)
print(arr3)

[1. 1. 1. 1.] float64
[1 1 1 1] int16
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [23]:
# Create an array of zeros using np.zeros() method

arr1 = np.zeros(4)
print(arr1, arr1.dtype)

arr2 = np.zeros(4, dtype=np.int16)
print(arr2, arr2.dtype)

arr3 = np.zeros((3,3), dtype=np.int16)
print(arr3)

[0. 0. 0. 0.] float64
[0 0 0 0] int16
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [24]:
# Create an array of random elements using np.empty() method
# The function empty creates an array whose initial content 
# is random and depends on the state of the memory.

arr1 = np.empty(4)
print(arr1, arr1.dtype)

arr2 = np.empty(4, dtype=np.int16)
print(arr2, arr2.dtype)

arr3 = np.empty((3,3), dtype=np.int16)
print(arr3)

[0. 0. 0. 0.] float64
[0 0 0 0] int16
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [25]:
# Create an array with elements whose values are spaced linearly in 
# a user specified interval
# np.linspace(start, end, numberOfElements)

arr1 = np.linspace(1, 10, 10, dtype=np.int16)
print(arr1)

arr2 = np.linspace(11, 20, 21)
print(arr2)
print("Length of array is:", len(arr2))

[ 1  2  3  4  5  6  7  8  9 10]
[11.   11.45 11.9  12.35 12.8  13.25 13.7  14.15 14.6  15.05 15.5  15.95
 16.4  16.85 17.3  17.75 18.2  18.65 19.1  19.55 20.  ]
Length of array is: 21


In [26]:
# To create an array within a user specified range
# use np.arange() method, stop element is excluded
# np.arange(start, stop, step)

arr1 = np.arange(10)
print(arr1)

arr2 = np.arange(4, 10)
print(arr2)

arr2 = np.arange(4, 20, 3)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 4  7 10 13 16 19]


## Add, Remove, Sort Elements in an array

### Add arrays using concatenation

In [27]:
# Add two array use np.concatenate()
# numpy.concatenate((a1, a2, ...), axis=0, out=None, dtpe,...)

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = np.concatenate((arr1,arr2)) 
print(arr3)

[1 2 3 4 5 6 7 8]


In [28]:
arr1 = np.array([[1,2,3,4],[10, 11, 12, 13]])
arr2 = np.array([[5,6,7,8],[15,16,17,18]])
print(arr1)
print()
print(arr2)
print()
print("Adding above arrays (axis is default, 0) gives")
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[[ 1  2  3  4]
 [10 11 12 13]]

[[ 5  6  7  8]
 [15 16 17 18]]

Adding above arrays (axis is default, 0) gives
[[ 1  2  3  4]
 [10 11 12 13]
 [ 5  6  7  8]
 [15 16 17 18]]


In [29]:
# Add two array use np.concatenate()
# If axis is None, arrays are flattened before use

arr1 = np.array([[1,2,3,4],[10, 11, 12, 13]])
arr2 = np.array([[5,6,7,8],[15,16,17,18]])
print(arr1)
print()
print(arr2)
print()
print("Adding above arrays with axis set to None gives")
arr3 = np.concatenate((arr1, arr2), axis=None)
print(arr3)
print(isinstance(arr3, np.ndarray))

[[ 1  2  3  4]
 [10 11 12 13]]

[[ 5  6  7  8]
 [15 16 17 18]]

Adding above arrays with axis set to None gives
[ 1  2  3  4 10 11 12 13  5  6  7  8 15 16 17 18]
True


In [30]:
# Add two array use np.concatenate()
# If axis is None, arrays are flattened before use

arr1 = np.array([[1,2,3,4],[10, 11, 12, 13]])
arr2 = np.array([[5,6,7,8],[15,16,17,18]])
print(arr1)
print()
print(arr2)
print()
print("Adding above arrays with axis set to 1 gives")
arr3 = np.concatenate((arr1, arr2), axis=1)
print(arr3)

[[ 1  2  3  4]
 [10 11 12 13]]

[[ 5  6  7  8]
 [15 16 17 18]]

Adding above arrays with axis set to 1 gives
[[ 1  2  3  4  5  6  7  8]
 [10 11 12 13 15 16 17 18]]


### Remove elements from array using remove method

In [31]:
# Remove elements from array using delete method
# np.delete(array, indexToRemove), index start with zero
# A copy of arr with the elements specified by obj removed. 
# Delete does not occur in-place.

arr1 = np.array([1,2,3,4,5])
# Index 3 means 4th element 
arr2 = np.delete(arr1, 3)
print(arr1, arr2)

[1 2 3 4 5] [1 2 3 5]


In [32]:
# Remove elements from array using delete method

arr1 = np.array([1,2,3,4,5])
# -1 means last element
arr2 = np.delete(arr1, -1) 
print(arr1, arr2)

[1 2 3 4 5] [1 2 3 4]


In [33]:
# Remove elements from array using delete method

arr1 = np.array([10,20,30,40,50])
# [2, 4] means elements at index 2 and 4
# elements at position 3 and position 5
arr2 = np.delete(arr1, [2,4]) 
print(arr1, arr2)

[10 20 30 40 50] [10 20 40]


In [34]:
# Remove elements from array using delete method

arr1 = np.array([10,20,30,40,50])

# Conditional deletion
arr2 = np.delete(arr1, np.where(arr1==30)) 
print(arr1, arr2)

[10 20 30 40 50] [10 20 40 50]


In [35]:
# Remove elements from array using delete method
# Delete columns (axis = 1)
arr1 = np.array([[3,2,5], [7,4,1], [6,5,4]])
print(arr1)

print()
# Delete the column at the 1st index
arr2 = np.delete(arr1, 1, axis=1) 
print(arr2)

print()
# Delete the column at the 0st index
arr2 = np.delete(arr1, 0, axis=1) 
print(arr2)

[[3 2 5]
 [7 4 1]
 [6 5 4]]

[[3 5]
 [7 1]
 [6 4]]

[[2 5]
 [4 1]
 [5 4]]


In [36]:
# Remove elements from array using delete method
# Delete array (axis = 0)
arr1 = np.array([[3,2,5], [7,4,1], [6,5,4]])
print(arr1)

print()
# Delete the 0th row
arr2 = np.delete(arr1, 1, axis=0) 
print(arr2)

print()
# Delete the first row
arr2 = np.delete(arr1, 0, axis=0) 
print(arr2)

print()
# Delete the 0th and 2nd rows
arr2 = np.delete(arr1, [0,2], axis=0) 
print(arr2)

[[3 2 5]
 [7 4 1]
 [6 5 4]]

[[3 2 5]
 [6 5 4]]

[[7 4 1]
 [6 5 4]]

[[7 4 1]]


### Sort elements using the sort method

In [37]:
# Sort an array in numpy using sort method
# numpy.sort(a, axis=-1, kind=None, order=None)
# Sort method returns a copy of the array, original array is unchanged

arr1 = np.array([3,1,9,5,4,6,8,2,7])
print("Array before sorting:", arr1)

print("Array after sorting:", np.sort(arr1))

print("Check the sort is permanent: ", arr1)

Array before sorting: [3 1 9 5 4 6 8 2 7]
Array after sorting: [1 2 3 4 5 6 7 8 9]
Check the sort is permanent:  [3 1 9 5 4 6 8 2 7]


In [38]:
# Axis along which to sort. If None, the array is flattened before sorting. 
# The default is -1, which sorts along the last axis.

arr1 = np.array([[3,2,5], [7,4,1], [6,5,4]])
print(np.sort(arr1))
print()

arr1 = np.array([[3,2,5], [7,4,1], [6,5,4]])
print(np.sort(arr1, axis=-1))
print()

arr1 = np.array([[3,2,5], [7,4,1], [6,5,4]])
print(np.sort(arr1, axis=None))
print()

# Sort done on the column
arr1 = np.array([[3,2,5], [7,4,1], [6,5,4]])
print(np.sort(arr1, axis=0))
print()


[[2 3 5]
 [1 4 7]
 [4 5 6]]

[[2 3 5]
 [1 4 7]
 [4 5 6]]

[1 2 3 4 4 5 5 6 7]

[[3 2 1]
 [6 4 4]
 [7 5 5]]



### Sum

In [39]:
arr1 = []
print(arr1)
print("Sum =",np.sum(arr1))
print()
arr1 = np.array([[3,2,5], [7,4,1], [6,5,4]])
print(arr1)
print("Sum =",np.sum(arr1))

[]
Sum = 0.0

[[3 2 5]
 [7 4 1]
 [6 5 4]]
Sum = 37


In [40]:
arr1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1)
print()
print("Sum =",np.sum(arr1))

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]

Sum = 243


In [41]:
arr1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1)
print()
print("Sum =",np.sum(arr1))
print()
print("Sum =",np.sum(arr1, axis=0))
print()
print("Sum =",np.sum(arr1, axis=1))

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]

Sum = 243

Sum = [[33 36 39]
 [42 45 48]]

Sum = [[ 5  7  9]
 [25 27 29]
 [45 47 49]]


### Max

In [42]:
arr1 = np.array([[3,2,5], [7,4,1], [6,5,4]])
print(arr1)
print("Max =",np.max(arr1))

[[3 2 5]
 [7 4 1]
 [6 5 4]]
Max = 7


In [43]:
arr1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1)
print()
print("Max =",np.max(arr1))

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]

Max = 26


In [44]:
arr1 = np.array([[[1,12,3],[14,5,6]],[[11,2,3],[4,5,16]]])
print(arr1)
print()
print("Max =",np.max(arr1, axis=0))
print()
print("Max =",np.max(arr1, axis=1))

[[[ 1 12  3]
  [14  5  6]]

 [[11  2  3]
  [ 4  5 16]]]

Max = [[11 12  3]
 [14  5 16]]

Max = [[14 12  6]
 [11  5 16]]


In [45]:
arr1 = np.array([[[1,12,3],[4,5,6]],[[11,12,13],[4,5,16]],[[21,22,23],[4,25,6]]])
print(arr1)
print()
print("Max =",np.max(arr1, axis=0))
print()
print("Max =",np.max(arr1, axis=1))

[[[ 1 12  3]
  [ 4  5  6]]

 [[11 12 13]
  [ 4  5 16]]

 [[21 22 23]
  [ 4 25  6]]]

Max = [[21 22 23]
 [ 4 25 16]]

Max = [[ 4 12  6]
 [11 12 16]
 [21 25 23]]


### Min

In [46]:
arr1 = np.array([[3,2,5], [7,4,1], [6,5,4]])
print(arr1)
print("Min =",np.min(arr1))

[[3 2 5]
 [7 4 1]
 [6 5 4]]
Min = 1


In [47]:
arr1 = np.array([[[100,20,30],[40,50,60]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1)
print()
print("Min =",np.min(arr1))

[[[100  20  30]
  [ 40  50  60]]

 [[ 11  12  13]
  [ 14  15  16]]

 [[ 21  22  23]
  [ 24  25  26]]]

Min = 11


In [48]:
arr1 = np.array([[[1,12,3],[14,5,6]],[[11,2,3],[4,5,16]]])
print(arr1)
print()
print("Min =",np.min(arr1, axis=0))
print()
print("Min =",np.min(arr1, axis=1))

[[[ 1 12  3]
  [14  5  6]]

 [[11  2  3]
  [ 4  5 16]]]

Min = [[1 2 3]
 [4 5 6]]

Min = [[1 5 3]
 [4 2 3]]


In [49]:
arr1 = np.array([[[1,12,3],[4,5,6]],[[11,12,13],[4,5,16]],[[21,22,23],[4,25,6]]])
print(arr1)
print()
print("Min =",np.min(arr1, axis=0))
print()
print("Min =",np.min(arr1, axis=1))

[[[ 1 12  3]
  [ 4  5  6]]

 [[11 12 13]
  [ 4  5 16]]

 [[21 22 23]
  [ 4 25  6]]]

Min = [[ 1 12  3]
 [ 4  5  6]]

Min = [[ 1  5  3]
 [ 4  5 13]
 [ 4 22  6]]


### Average

In [50]:
arr1 = np.array([[3,2,4], [7,4,1], [6,5,4]])
print(arr1)
print("Average =",np.average(arr1))

[[3 2 4]
 [7 4 1]
 [6 5 4]]
Average = 4.0


In [51]:
arr1 = np.array([[[100,20,30],[40,50,60]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1)
print()
print("Average =",np.average(arr1))

[[[100  20  30]
  [ 40  50  60]]

 [[ 11  12  13]
  [ 14  15  16]]

 [[ 21  22  23]
  [ 24  25  26]]]

Average = 29.0


In [52]:
arr1 = np.array([[[1,12,3],[14,5,6]],[[11,2,3],[4,5,16]]])
print(arr1)
print()
print("Average =",np.average(arr1, axis=0))
print()
print("Average =",np.average(arr1, axis=1))

[[[ 1 12  3]
  [14  5  6]]

 [[11  2  3]
  [ 4  5 16]]]

Average = [[ 6.  7.  3.]
 [ 9.  5. 11.]]

Average = [[7.5 8.5 4.5]
 [7.5 3.5 9.5]]


In [53]:
arr1 = np.array([[[1,12,3],[4,5,6]],[[11,12,13],[4,5,16]],[[21,22,23],[4,25,6]]])
print(arr1)
print()
print("Average =",np.average(arr1, axis=0))
print()
print("Average =",np.average(arr1, axis=1))

[[[ 1 12  3]
  [ 4  5  6]]

 [[11 12 13]
  [ 4  5 16]]

 [[21 22 23]
  [ 4 25  6]]]

Average = [[11.         15.33333333 13.        ]
 [ 4.         11.66666667  9.33333333]]

Average = [[ 2.5  8.5  4.5]
 [ 7.5  8.5 14.5]
 [12.5 23.5 14.5]]
